### ISSUE TITLE
New Feature: Semantic Segmentation

### ISSUE THREAD

**Issue by erentknn** [jrieke/traingenerator#2]
I started to work on semantic segmentation with TF/Keras. i will mainly use [segmentation models library](https://github.com/qubvel/segmentation_models), if you have any suggestions or if you want to help feel free to contact me!

**Comment by jrieke** [comment]
Thx for your effort @erentknn! You are welcome to open a work in progress PR as soon as you like, so I can give feedback (mark with [WIP]).

**Comment by jrieke** [comment]
Hey @erentknn, any progress on this so far? @The-ML-Hero was also thinking about working on segmentation (see #15), just want to coordinate so you don't do duplicate work :)

**Comment by erentknn** [comment]
hey @jrieke I worked on for a while but currently i cant make any progress because of work and grad school. So he can work on Semantic Segmentation. I am closing this.
