### ISSUE TITLE
tabular regression and classification

### ISSUE THREAD

**Issue by atwahsz** [jrieke/traingenerator#8]
RNN (LSTM) , CNN

**Comment by jrieke** [comment]
I guess you want a new template for this? Can you describe in more detail what your use case is and which framework you would want?

**Comment by atwahsz** [comment]
tabular data regression

**Comment by jrieke** [comment]
@atwahsz I'm closing this for now. If you have a more complete explanation of what you want, please feel free to write it here, then I'll re-open :)
